@startuml

participant RBFM as R
participant Record as RC
participant DataPage as D
participant FileHandle as F

==init==
R -> RC: rawData, descriptor
RC -> R: Record
R -> D: pageID
D -> R: Page

==if can't fit into original page==
R -> R: getFirstPageAvailable()

==update==
R -> D: Record, slotID
activate D
D -> D: moveRecords()\nmemcpy()
D -> D: update slots' offsets\nfreespace, record number
D -> R
deactivate D

==save==
R -> F: pageNum, *pageData, freeSpace
F -> F: writePage(pageNum, freeSpace, *pageData)
F -> R
@enduml